- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "testxxx"
  color: "a2eeef"
  description: "New feature or request"
  from_name: "test"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
