- name: type/bug
  color: D4C5F9
  description: Is a bug report
  from_name: bug
- name: area/documentation
  color: F9D0C4
  description: Belongs to documentation
  from_name: documentation
- name: status/duplicate
  color: cfd3d7
  description: There were an existing issue
  from_name: duplicate
- name: type/help-needed
  color: D4C5F9
  description: Extra attention is needed
  from_name: help wanted
- name: area/tests
  color: F9D0C4
  description: Belongs to tests
  from_name: "test"
