- name: "bug"
  color: "fc2929"
  description: ""
- name: "duplicate"
  color: "cccccc"
  description: ""
- name: "enhancement"
  color: "84b6eb"
  description: ""
- name: "help wanted"
  color: "159818"
  description: ""
- name: "invalid"
  color: "e6e6e6"
  description: ""
- name: "question"
  color: "cc317c"
  description: ""
- name: "wontfix"
  color: "ffffff"
  description: ""
- name: "task"
  color: "d4c5f9"
  description: ""
- name: "test"
  color: "fbca04"
  description: ""
- name: "jepsen"
  color: "fef2c0"
  description: ""
- name: "docs"
  color: "207de5"
  description: ""
- name: "backport"
  color: "5319e7"
  description: ""
- name: "Epic"
  color: "3E4B9E"
  description: ""
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "blocker"
  color: "c40d2c"
  description: ""