name: Composite Test1

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test composite
      uses: ./.github/actions/build-images
      with:
        version: 1.2.3-SNAPSHOT
