name: Inputs1

on:
  workflow_dispatch:
    inputs:
      key1:
        description: 'key1'
        required: true
        default: 'val1'
      key2:
        description: 'key2'
        required: true
      key3:
        description: 'key3'
        required: false
        default: 'val3'
      key4:
        description: 'key4'
        required: false

env:
  INPUT_KEY1: ${{ github.event.inputs.key1 }}
  INPUT_KEY2: ${{ github.event.inputs.key2 }}
  INPUT_KEY3: ${{ github.event.inputs.key3 }}
  INPUT_KEY4: ${{ github.event.inputs.key4 }}

jobs:
  testInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Extract Inputs
      run: |
        echo VAL1=${INPUT_KEY1=-bar1} >> $GITHUB_ENV
        echo VAL2=${INPUT_KEY2=-bar2} >> $GITHUB_ENV
        echo VAL3=${INPUT_KEY3=-bar3} >> $GITHUB_ENV
        echo VAL4=${INPUT_KEY4=-bar4} >> $GITHUB_ENV
    - name: Use Inputs
      run: |
        echo VAL1: $VAL1
        echo VAL2: $VAL2
        echo VAL3: $VAL3
        echo VAL4: $VAL4
