name: IssueHandle1

on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:

    - name: Handle Issues
      uses: jvalkeal/issue-handler@initial-work
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config: >
          {
            "recipes": [
              {
                "name": "Mark new issue to get triaged",
                "type": "ifThen",
                "if": "isEvent('issues') && isAction('opened') && !isMilestone() && !hasLabels()",
                "then": "labelIssue(['status/need-triage'])"
              },
              {
                "name": "Create net backport issues",
                "type": "manageBackportIssues",
                "whenLabeled": "labeledStartsWith(['branch/'])",
                "whenLabels": "labelsContains(['for/backport'])",
                "fromLabels": "labeledStartsWith(['branch/'])",
                "additionalLabels": "'type/backport'",
                "title": "title",
                "body": "'Backport #' + number"
              }
            ]
          }
