name: Jfrog1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.43.2
    - name: Configure JFrog Cli
      run: |
        jfrog rt gradlec \
          --server-id-resolve=local \
          --server-id-deploy=local \
          --repo-resolve=libs-snapshot \
          --repo-deploy=libs-snapshot \
          --use-wrapper=true
        echo JFROG_CLI_BUILD_NAME=test-build-project >> $GITHUB_ENV
        echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
        echo JFROG_CLI_BUILD_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID >> $GITHUB_ENV
    - name: Echo jfrog stuff
      run: |
          echo JFROG_CLI_LOG_LEVEL $JFROG_CLI_LOG_LEVEL
          echo JFROG_CLI_OFFER_CONFIG $JFROG_CLI_OFFER_CONFIG
          echo JFROG_CLI_HOME_DIR $JFROG_CLI_HOME_DIR
          echo JFROG_CLI_TEMP_DIR $JFROG_CLI_TEMP_DIR
          echo JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NAME
          echo JFROG_CLI_BUILD_NUMBER $JFROG_CLI_BUILD_NUMBER
          echo JFROG_CLI_BUILD_PROJECT $JFROG_CLI_BUILD_PROJECT
          echo JFROG_CLI_BUILD_URL $JFROG_CLI_BUILD_URL
          echo JFROG_CLI_ENV_EXCLUDE $JFROG_CLI_ENV_EXCLUDE
