name: Labeler1

on:
  issues:
    types: [labeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Handle Zoo Control
      uses: jvalkeal/issue-handler@initial-work
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config: >
          {
            "actions": [
              {
                "type": "ifThen",
                "if": "hasLabels(['for/backport'])",
                "then": "createIssue()"
              }
            ]
          }
