name: Release1

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_NOTES_FILE: ${{runner.temp}}/release_notes.md5
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version: 2.8.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version: 2.8.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_deployer_version: 2.6.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version: 2.6.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version: 2.6.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version: 2.6.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version: 1.6.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_skipper_version: 2.7.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version: 3.1.0-RC1
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_version: 2.8.0-RC1

        run: |
          echo "#Release Notes"
          echo "## Dependent Projects and Compatibility"
          echo "Component | Version"
          echo "--- | ---"
          echo "Spring Cloud Dataflow Build | $BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version"
          echo "Spring Cloud Dataflow Common | $BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version"
          echo "Spring Cloud Dataflow Deployer | $BUILD_ZOO_HANDLER_spring_cloud_deployer_version"
          echo "Spring Cloud Dataflow Deployer Local | $BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version"
          echo "Spring Cloud Dataflow Deployer CF | $BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version"
          echo "Spring Cloud Dataflow Deployer K8S | $BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version"
          echo "Spring Cloud Common Security Config | $BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version"
          echo "Spring Cloud Skipper | $BUILD_ZOO_HANDLER_spring_cloud_skipper_version"
          echo "Spring Cloud Dataflow UI | $BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version"
          echo "Spring Cloud Dataflow Build | $BUILD_ZOO_HANDLER_spring_cloud_dataflow_version"
          echo "## Issues"

          gh issue list \
            --repo spring-cloud/spring-cloud-dataflow-build \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-dataflow-build#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-dataflow-common \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-dataflow-common#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-deployer \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_deployer_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-deployer#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-deployer-local \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-deployer-local#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-deployer-cloudfoundry \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-deployer-cloudfoundry#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-deployer-kubernetes \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-deployer-kubernetes#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-common-security-config \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-common-security-config#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-skipper \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_skipper_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-skipper#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-dataflow-ui \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-dataflow-ui#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE
          gh issue list \
            --repo spring-cloud/spring-cloud-dataflow \
            --milestone BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \
            --state all --json number,title \
            --template "{{range .}}spring-cloud/spring-cloud-dataflow#{{.number}} {{.title}}{{\"\n\"}}{{end}}" \
            >> $RELEASE_NOTES_FILE

          gh release create v$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \
            --title "Spring Cloud Data Flow $BUILD_ZOO_HANDLER_spring_cloud_dataflow_version" \
            --notes-file $RELEASE_NOTES_FILE
