name: Release3

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Tooling
      run: |
        curl -sSL https://github.com/cbroglie/mustache/releases/download/v1.2.2/mustache_1.2.2_linux_amd64.tar.gz | sudo tar -C /usr/local/bin/ --no-same-owner -xzv mustache
    - name: Build
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RELEASE_NOTES_FILE: ${{runner.temp}}/release_notes.md5
        RELEASE_NOTES_DATA: ${{runner.temp}}/release_notes_data.json
        RELEASE_NOTES_HEADERS1: ${{runner.temp}}/release_notes_headers1.json
        RELEASE_NOTES_ISSUES1: ${{runner.temp}}/release_notes_issues1.json
        RELEASE_NOTES_ISSUES2: ${{runner.temp}}/release_notes_issues2.json
        RELEASE_NOTES_ISSUES3: ${{runner.temp}}/release_notes_issues3.json
        RELEASE_NOTES_ISSUES4: ${{runner.temp}}/release_notes_issues4.json
        RELEASE_NOTES_ISSUES5: ${{runner.temp}}/release_notes_issues5.json
        RELEASE_NOTES_ISSUES6: ${{runner.temp}}/release_notes_issues6.json
        RELEASE_NOTES_ISSUES7: ${{runner.temp}}/release_notes_issues7.json
        RELEASE_NOTES_ISSUES8: ${{runner.temp}}/release_notes_issues8.json
        RELEASE_NOTES_ISSUES9: ${{runner.temp}}/release_notes_issues9.json
        RELEASE_NOTES_ISSUES10: ${{runner.temp}}/release_notes_issues10.json
        BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version: 2.8.1
        BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version: 2.8.1
        BUILD_ZOO_HANDLER_spring_cloud_deployer_version: 2.6.1
        BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version: 2.6.1
        BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version: 2.6.1
        BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version: 2.6.1
        BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version: 1.6.1
        BUILD_ZOO_HANDLER_spring_cloud_skipper_version: 2.7.1
        BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version: 3.1.1
        BUILD_ZOO_HANDLER_spring_cloud_dataflow_version: 2.8.1

      run: |
        gh issue list \
          --repo jvalkeal/atest6 \
          --milestone 0.0.1 \
          --label xxx/rlnotes \
          --state all --json title,body \
          --jq '{headers:map(.)}' \
          > $RELEASE_NOTES_HEADERS1
        gh issue list \
          --repo spring-cloud/spring-cloud-dataflow-build \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_dataflow_build_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-dataflow-build"})}' \
          > $RELEASE_NOTES_ISSUES1
        gh issue list \
          --repo spring-cloud/spring-cloud-dataflow-common \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_dataflow_common_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-dataflow-common"})}' \
          > $RELEASE_NOTES_ISSUES2
        gh issue list \
          --repo spring-cloud/spring-cloud-deployer \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_deployer_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-deployer"})}' \
          > $RELEASE_NOTES_ISSUES3
        gh issue list \
          --repo spring-cloud/spring-cloud-deployer-local \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_deployer_local_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-deployer-local"})}' \
          > $RELEASE_NOTES_ISSUES4
        gh issue list \
          --repo spring-cloud/spring-cloud-deployer-cloudfoundry \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_deployer_cloudfoundry_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-deployer-cloudfoundry"})}' \
          > $RELEASE_NOTES_ISSUES5
        gh issue list \
          --repo spring-cloud/spring-cloud-deployer-kubernetes \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_deployer_kubernetes_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-deployer-kubernetes"})}' \
          > $RELEASE_NOTES_ISSUES6
        gh issue list \
          --repo spring-cloud/spring-cloud-common-security-config \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_common_security_config_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-common-security-config"})}' \
          > $RELEASE_NOTES_ISSUES7
        gh issue list \
          --repo spring-cloud/spring-cloud-skipper \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_skipper_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-skipper"})}' \
          > $RELEASE_NOTES_ISSUES8
        gh issue list \
          --repo spring-cloud/spring-cloud-dataflow-ui \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_dataflow_ui_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-dataflow-ui"})}' \
          > $RELEASE_NOTES_ISSUES9
        gh issue list \
          --repo spring-cloud/spring-cloud-dataflow \
          --milestone $BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \
          --state all --json number,title,labels \
          --jq '{issues:map(select( any(.labels[]; .name != "xxx/rlnotes" )) + {repo:"spring-cloud/spring-cloud-dataflow"})}' \
          > $RELEASE_NOTES_ISSUES10
        jq -s '{issues:(.[0].issues + .[1].issues + .[2].issues + .[3].issues + .[4].issues + .[5].issues + .[6].issues + .[7].issues + .[8].issues + .[9].issues), headers:(.[10].headers)}' \
          $RELEASE_NOTES_ISSUES1 \
          $RELEASE_NOTES_ISSUES2 \
          $RELEASE_NOTES_ISSUES3 \
          $RELEASE_NOTES_ISSUES4 \
          $RELEASE_NOTES_ISSUES5 \
          $RELEASE_NOTES_ISSUES6 \
          $RELEASE_NOTES_ISSUES7 \
          $RELEASE_NOTES_ISSUES8 \
          $RELEASE_NOTES_ISSUES9 \
          $RELEASE_NOTES_ISSUES10 \
          $RELEASE_NOTES_HEADERS1 \
          > $RELEASE_NOTES_DATA
        mustache $RELEASE_NOTES_DATA .github/rlnotes.mustache > $RELEASE_NOTES_FILE
        gh release create v$BUILD_ZOO_HANDLER_spring_cloud_dataflow_version \
          --draft \
          --title "Spring Cloud Data Flow $BUILD_ZOO_HANDLER_spring_cloud_dataflow_version" \
          --notes-file $RELEASE_NOTES_FILE
