name: Release1

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VALUES='
          2.8.0-RC1,spring-cloud-dataflow-build
          2.8.0-RC1,spring-cloud-dataflow-common
          2.6.0-RC1,spring-cloud-deployer
          2.6.0-RC1,spring-cloud-deployer-local
          2.6.0-RC1,spring-cloud-deployer-cloudfoundry
          2.6.0-RC1,spring-cloud-deployer-kubernetes
          1.6.0-RC1,spring-cloud-common-security-config
          2.7.0-RC1,spring-cloud-skipper
          3.1.0-RC1,spring-cloud-dataflow-ui
          2.8.0-RC1,spring-cloud-dataflow
          '
          for VALUE in $VALUES;
            do
              MILESTONE=$(echo $VALUE | cut -f1 -d,)
              REPO=$(echo $VALUE | cut -f2 -d,)
              TEMPLATE="{{range .}}spring-cloud/$REPO#{{.number}} {{.title}}{{\"\n\"}}{{end}}"
              gh issue list --repo spring-cloud/$REPO --milestone $MILESTONE --state all --json number,title --template "$TEMPLATE"
          done;
