name: Test4

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jvalkeal/setup-maven@master
      with:
        maven-version: 3.6.2
