name: Diff Test1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Diff
      run: |
        out="$(diff file1.txt file2.txt)" || true
        if [ -n "$out" ]; then
          echo "::warning ::Diff $out"
        fi
