name: Java1

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      - name: run tests
        run: |
          java --version
