name: Diff Test1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Diff
      run: |
        raw="$(diff file1.txt file2.txt)" || true
        len="${#raw}"
        out=""
        for (( i = 0; i < len; i++ )); do
          c="${raw:$i:1}"
          case $c in
            [a-zA-Z0-9.~_-,\<\>' ']) out+=$(printf '%s' "$c") ;;
            *) out+=$(printf '%%%02X' "'$c") ;;
          esac
        done
        if [ -n "$out" ]; then
          echo "::warning ::Diff $out"
        fi
