name: Test6

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: say hi
      run: |
        echo hi2
