name: Diff Test1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Diff
      run: |
        text="This is error1\nThis is error2"
        text="${text//'\n'/'%0A'}" #replace '\n' with '%0A'
        echo $text
        echo "::error file=app.js,line=10,col=15::$text"
