name: Diff Test1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Diff
      run: |
        out="$(diff file1.txt file2.txt)" || true
        out="${out//'\n'/'%0A'}"
        out="${out//'<'/'%3C'}"
        out="${out//'>'/'%3E'}"
        if [ -n "$out" ]; then
          echo "::error ::Diff $out"
        fi
