name: Slack Notification Demo

on:
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Check Links
      uses: jvalkeal/link-check@main
      id: sitelinkcheck
      with:
        url: https://dataflow-staging.apps.pcfone.io/docs/installation/kubernetes/helm

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ fromJson(steps.sitelinkcheck.outputs.results).status == false }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ toJson(steps.sitelinkcheck.outputs.results) }}
        SLACK_TITLE: Hi from link check
