name: Labeler Test1

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jvalkeal/ghaction-github-labeler@gh120-work1
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue