name: Staging Check

on:
  workflow_dispatch:

jobs:
  sitecheck:
    name: Slack Notification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
        - /
        - /docs/2.8.0.SNAPSHOT
    steps:
    - uses: actions/checkout@v2
    - name: Check Links
      uses: jvalkeal/link-check@main
      id: sitelinkcheck
      with:
        url: https://dataflow-staging.apps.pcfone.io${{ matrix.path }}
        fail: false
        config: >
          {
            "recurse": true,
            "concurrency": 30,
            "skip": [
              "^data:image",
              "^http://localhost:9393",
              "^https://localhost:9393",
              "^http://localhost:9090",
              "^http://localhost:3000",
              "^http://localhost:15672",
              "^http://localhost:7577",
              "^http://localhost:8086",
              "^http://192.168.99.100",
              "^http://stateless.co",
              "^http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/"
            ],
            "throttlelimit": 1,
            "throttleinterval": 1000,
            "throttle": [
              "^https://github.com",
              "^https://github.githubassets.com"
            ]
          }
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ fromJson(steps.sitelinkcheck.outputs.results).status == true }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ toJson(fromJson(steps.sitelinkcheck.outputs.results).brokenLinks) }}
        SLACK_TITLE: Link Check Failures https://dataflow-staging.apps.pcfone.io${{ matrix.path }}
