name: Slack Notification Demo

on:
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Check Links
      uses: jvalkeal/link-check@main
      id: sitelinkcheck
      with:
        url: https://dataflow-staging.apps.pcfone.io
        linkinator-config: >
          {
            "recurse": true,
            "concurrency": 10,
            "skip": [
              "^data:image",
              "^http://localhost:9393",
              "^https://localhost:9393",
              "^http://localhost:9090",
              "^http://localhost:3000",
              "^http://localhost:15672",
              "^http://localhost:7577",
              "^http://localhost:8086",
              "^http://192.168.99.100",
              "^http://stateless.co",
              "^http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/"
            ],
            "throttlelimit": 1,
            "throttleinterval": 1000,
            "throttle": [
              "^https://github.com",
              "^https://github.githubassets.com"
            ]
          }

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ fromJson(steps.sitelinkcheck.outputs.results).status == false }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ toJson(steps.sitelinkcheck.outputs.results) }}
        SLACK_TITLE: Hi from link check
