name: Diff Test1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Diff
      run: |
        raw="$(diff file1.txt file2.txt)" || true
        out="${raw//'\n'/'%0A'}"
        if [ -n "$out" ]; then
          echo "::warning ::Diff %0A for files"
        fi
