name: Build Multi Step1

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo hi > data.txt
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.txt

  promote:
    runs-on: ubuntu-latest
    needs: build
    environment: promote
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: data
      - name: Output data
        run: |
          cat data.txt

  central:
    runs-on: ubuntu-latest
    needs: promote
    environment: central
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: data
      - name: Output data
        run: |
          cat data.txt
