name: Test5

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - name: run maven
      run: mvn build-helper:parse-version
