name: Labeler Test2

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rename Labels
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/rename-labels.yml
          dry-run: false
          skip-delete: true
