name: Test6

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: say hi
      run: |
        echo hi2
