name: Tmc1

on:
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: jvalkeal/tmc-toolkit@main
        with:
          org: ${{ secrets.TMC_ORG }}
      - name: Output
        run: |
          tmc version
