name: Tmc1

on:
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: jvalkeal/tmc-toolkit@gh2-work1
        with:
          org: ${{ secrets.TMC_ORG }}
          token: ${{ secrets.TMC_API_TOKEN }}
          management-cluster-name: aws-hosted
          provisioner-name: scdf-provisioner
      # - name: Configure tmc
      #   env:
      #     TMC_API_TOKEN: ${{ secrets.TMC_API_TOKEN }}
      #   run: |
      #     tmc login --name dummy --no-configure
      #     tmc configure --management-cluster-name aws-hosted --provisioner-name scdf-provisioner
      - name: Output
        run: |
          tmc cluster list
