name: Tmc1

on:
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: tmc1
        uses: jvalkeal/tmc-toolkit@gh2-work1
        with:
          org: ${{ secrets.TMC_ORG }}
          token: ${{ secrets.TMC_API_TOKEN }}
          context-name: test1
          management-cluster-name: aws-hosted
          provisioner-name: scdf-provisioner
      - name: tmc2
        uses: jvalkeal/tmc-toolkit@gh2-work1
        with:
          org: ${{ secrets.TMC_ORG }}
          token: ${{ secrets.TMC_API_TOKEN }}
          context-name: test2
          management-cluster-name: aws-hosted
          provisioner-name: scdf-provisioner
      - name: Output
        run: |
          tmc cluster list
