name: Wait1

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
       echo TEST_IP=google.com >> $GITHUB_ENV
    - name: Wait
      uses: ./.github/actions/wait-http
      with:
        url: http://${{ env.TEST_IP }}
