name: Zoo1

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: false
      build-zoo-handler-properties:
        description: 'Define milestone version as milestone_version=M1'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Handle Zoo Control
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        dispatch-handler-token: ${{ secrets.PAT }}
        dispatch-handler-max: 15
        dispatch-handler-config: >
          [
            {
              "if": "initial == true",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "jvalkeal",
                "repo": "atest5",
                "ref": "master",
                "workflow": "zoo2.yml"
              }
            }
          ]
